const mediumRules = ['permission', 'validation', 'sanitization', 'leak', 'weak', 'missing', 'eval', 'allocation', 'potential-dos', 'verbose-error', 'unvalidated-data', 'log', 'timing', 'crypto-misuse', 'microservice'];

// prettier-ignore
const mediumSeverityRules = [
    'js/overly-permissive-regular-expression',
    'js/insecure-cookie',
    'js/cors-misconfiguration',
    'js/overly-permissive-file-upload',
    'js/redos',
    'js/client-side-unvalidated-redirect',
    'js/weak-cryptographic-algorithm',
    'js/information-disclosure',
    'js/email-leak',
    'js/uncontrolled-format-string',
    'js/dom-based-property-injection',
    'js/uncontrolled-memory-allocation',
    'js/signature-verification-bypass',
    'js/csv-injection',
    'js/overly-large-range',
    'js/loop-iteration-skipped-due-to-shifting',
    'js/potential-dos',
    'js/verbose-error-messages',
    'js/unvalidated-data-in-log',
    'js/log-injection',
    'js/timing-attack',
    'js/web-crypto-misuse',
    'js/microservice-auth-bypass',
    'js/unsafe-external-link',
    'js/missing-csrf-protection',
    'js/session-fixation',
    'js/clickjacking-vulnerability'
];

const mediumDescriptions = {
	'js/overly-permissive-regular-expression': 'Regular expression is too permissive or contains inefficient patterns, potentially allowing unwanted input to pass validation, causing regular expression denial of service (ReDoS), or failing to properly validate security-critical input in authentication or authorization contexts.',
	'js/insecure-cookie': 'Cookies configured without proper security attributes like Secure, HttpOnly, or SameSite, potentially making them vulnerable to theft through man-in-the-middle attacks, cross-site scripting exploitation, or cross-site request forgery in modern web applications.',
	'js/cors-misconfiguration': 'Cross-Origin Resource Sharing (CORS) misconfiguration that allows unauthorized websites to access sensitive information, potentially enabling data theft, credential harvesting, or bypassing same-origin policy protections through overly permissive policies.',
	'js/overly-permissive-file-upload': 'File upload functionality that lacks proper restrictions on file types, sizes, or content validation, potentially allowing malicious files to be uploaded, stored, and executed, leading to remote code execution or server compromise.',
	'js/redos': 'Regular Expression Denial of Service vulnerability where certain inputs can cause a regular expression to exhibit catastrophic backtracking, leading to excessive CPU consumption, application hangs, or service unavailability.',
	'js/client-side-unvalidated-redirect': 'Client-side redirection without proper validation allows attackers to redirect users to malicious sites through crafted URLs, potentially enabling phishing attacks, malware distribution, or credential theft through trusted domain abuse.',
	'js/weak-cryptographic-algorithm': 'Use of cryptographic algorithms considered weak by current security standards (e.g., MD5, SHA1, DES, RC4), potentially making encrypted data vulnerable to cryptographic attacks, rainbow table attacks, or collision attacks.',
	'js/information-disclosure': 'Unnecessary exposure of internal information such as stack traces, server versions, internal paths, database schemas, or system configurations that could aid attackers in reconnaissance and targeted exploitation.',
	'js/email-leak': 'Email addresses or email content exposed in ways that could be collected by attackers for phishing campaigns, spam distribution, social engineering attacks, or targeted surveillance through email harvesting.',
	'js/uncontrolled-format-string': 'Format string vulnerability where user input is directly used in format strings without proper validation, potentially leading to information disclosure, memory corruption, or in some cases arbitrary code execution.',
	'js/dom-based-property-injection': 'DOM-based property injection vulnerability where user input can control DOM element properties, potentially leading to cross-site scripting, clickjacking, or other client-side attacks through manipulation of element attributes or behavior.',
	'js/uncontrolled-memory-allocation': 'Uncontrolled memory allocation vulnerability where user input can cause excessive memory consumption without proper bounds checking, potentially leading to denial of service, out-of-memory conditions, or system instability.',
	'js/signature-verification-bypass': 'Signature verification bypass vulnerability where cryptographic signatures can be circumvented or improperly validated, allowing attackers to tamper with signed data, forge digital signatures, or bypass integrity checks.',
	'js/csv-injection': 'CSV injection vulnerability where malicious formula commands can be injected into CSV exports, potentially leading to data theft, malware execution when opened in spreadsheet applications, or remote code execution on end-user systems.',
	'js/overly-large-range': 'Overly large range vulnerability occurs when a function operates on an excessively large range of input without proper bounds checking, potentially leading to performance degradation, memory exhaustion, denial of service, or integer overflow conditions.',
	'js/loop-iteration-skipped-due-to-shifting': 'Modifying an array during iteration (adding/removing elements) can cause elements to be skipped or processed multiple times, resulting in incomplete data processing, logic errors, or security bypass through incomplete validation.',
	'js/potential-dos': 'Potential denial of service vulnerability where certain inputs or operations may cause excessive resource consumption, infinite loops, inefficient algorithms, or regex patterns leading to application unavailability or performance degradation.',
	'js/verbose-error-messages': 'Error messages that reveal sensitive information, such as stack traces, database queries, server configurations, or internal application details, potentially aiding attackers in reconnaissance or providing information for targeted exploitation.',
	'js/unvalidated-data-in-log': 'Logging unvalidated user data potentially allows attackers to inject malicious content into logs, leading to log forging, obfuscation of attack traces, or exploitation of log processing systems.',
	'js/log-injection': 'Log injection vulnerability where unvalidated user input is logged without proper sanitization, potentially allowing attackers to inject malicious content to forge log entries, obscure malicious activities, or exploit log analysis tools.',
	'js/timing-attack': 'Timing attack vulnerability where response times or processing delays leak sensitive information, potentially allowing attackers to infer secret values, bypass authentication through timing analysis, or extract cryptographic keys through side-channel analysis.',
	'js/web-crypto-misuse': 'Misuse of Web Crypto API or cryptographic functions leading to weak encryption implementations, potentially exposing encrypted data to attacks due to improper key generation, algorithm selection, initialization vector reuse, or parameter configuration.',
	'js/microservice-auth-bypass': 'Authentication bypass in microservice architectures where inter-service communication lacks proper authentication or authorization, potentially allowing lateral movement within the service mesh, privilege escalation, or unauthorized access to internal services.',
	'js/unsafe-external-link': 'Unsafe external links that lack proper validation or security attributes, potentially leading to tabnabbing attacks, phishing through trusted domains, or unintended information disclosure through referrer headers when users navigate to external sites.',
	'js/missing-csrf-protection': 'Missing Cross-Site Request Forgery protection on state-changing operations, potentially allowing attackers to trick authenticated users into performing unintended actions through malicious websites or social engineering.',
	'js/session-fixation': 'Session fixation vulnerability where session identifiers are not properly regenerated after authentication, potentially allowing attackers to hijack user sessions by forcing the use of known session IDs.',
	'js/clickjacking-vulnerability': 'Clickjacking vulnerability where the application can be embedded in malicious frames, potentially allowing attackers to trick users into clicking on hidden elements, performing unintended actions, or disclosing sensitive information through UI redressing attacks.'
};

const mediumRecommendations = {
	'js/overly-permissive-regular-expression': 'Make regular expressions more specific and restrictive using anchors (^ and $) to match entire input. Test patterns against malicious inputs, implement timeouts for regex operations, consider using regex validation libraries with built-in safety, and use alternative parsing methods for complex validation.',
	'js/insecure-cookie': 'Configure all cookies with appropriate security attributes: Secure flag for HTTPS connections, HttpOnly to prevent XSS access, SameSite=Strict or Lax for CSRF protection. Implement proper cookie expiration times, use cookie prefixes like __Secure- for additional security, and regularly audit cookie configurations.',
	'js/cors-misconfiguration': 'Restrict CORS to specific trusted origins using exact domain matching instead of wildcards (*). Limit allowed HTTP methods to only what is necessary, restrict allowed headers, disable credentials for untrusted origins, and implement proper preflight request handling.',
	'js/overly-permissive-file-upload': 'Validate file types using MIME type detection and content inspection rather than extension alone. Implement strict file size limits, scan uploads for malware using antivirus integration, store uploaded files outside the web root, and use sandboxed environments for file processing.',
	'js/redos': 'Avoid using vulnerable regex patterns with nested quantifiers and alternation. Test regex performance against pathological inputs, use regex libraries with time limits or built-in ReDoS protection, consider using alternative parsing approaches like state machines or parser generators.',
	'js/client-side-unvalidated-redirect': 'Validate all redirect URLs against strict allowlists of permitted domains. Use relative URLs where possible, implement server-side validation even for client-side redirects, log all redirect attempts for monitoring, and consider using indirect redirects through lookup tables.',
	'js/weak-cryptographic-algorithm': 'Replace weak cryptographic algorithms with modern alternatives: use SHA-256 or SHA-3 instead of MD5/SHA1, AES-256 instead of DES/3DES, and secure key derivation functions like PBKDF2, scrypt, or Argon2. Keep cryptographic libraries updated and follow current NIST recommendations.',
	'js/information-disclosure': 'Minimize exposure of internal details in error messages, HTTP headers, and source code comments. Implement proper exception handling with generic error messages for production, remove debugging information from production builds, and use security headers to prevent information leakage.',
	'js/email-leak': 'Obfuscate email addresses in public-facing content using techniques like CSS hiding or JavaScript generation. Implement rate limiting for email-related functionality, use CAPTCHA for public forms, monitor for email harvesting attempts, and consider using contact forms instead of direct email display.',
	'js/uncontrolled-format-string': 'Avoid using user input in format string parameters entirely. Use template literals or safer string formatting methods that don\'t interpret format specifiers from user input. If formatting is necessary, validate and sanitize all inputs with strict allowlists.',
	'js/dom-based-property-injection': 'Sanitize all user input before using it to set DOM properties using libraries like DOMPurify. Use safe DOM APIs like textContent instead of innerHTML, validate property names against allowlists, and implement Content Security Policy to mitigate injection attacks.',
	'js/uncontrolled-memory-allocation': 'Implement strict limits on memory allocation based on available system resources. Validate and limit user input size before processing, use pagination or streaming for large data sets, implement resource monitoring and alerts, and use memory-efficient algorithms and data structures.',
	'js/signature-verification-bypass': 'Always verify signatures using constant-time comparison functions to prevent timing attacks. Validate all components of signed data including timestamps and context, use established cryptographic libraries, keep signature verification libraries updated, and implement comprehensive error handling.',
	'js/csv-injection': 'Sanitize all data used in CSV exports by escaping formula triggers (=, +, -, @, \t, \r). Prefix potentially dangerous cells with apostrophes or quotes, use CSV export libraries with built-in protections, validate all data before export, and educate users about risks of opening untrusted CSV files.',
	'js/overly-large-range': 'Implement proper bounds checking for all range operations with reasonable upper limits. Set maximum values for ranges in loops and data processing functions, use pagination or streaming for large data sets instead of processing all at once, and implement resource monitoring and timeouts.',
	'js/loop-iteration-skipped-due-to-shifting': 'Avoid modifying arrays during iteration by creating copies before iterating. Iterate in reverse order when removing elements, use array methods like filter() or map() instead of direct modification, and implement proper index management for complex iteration patterns.',
	'js/potential-dos': 'Implement comprehensive input validation to limit resource-intensive operations. Add timeouts for long-running processes, use efficient algorithms and data structures, implement resource monitoring and throttling, and consider using regex libraries with backtracking protection for pattern matching.',
	'js/verbose-error-messages': 'Use generic error messages in production environments that don\'t reveal internal details. Log detailed errors server-side only for debugging, implement environment-specific error handling, remove stack traces from client responses, and use error codes instead of descriptive messages.',
	'js/unvalidated-data-in-log': 'Sanitize and validate all user data before logging using logging frameworks with built-in redaction capabilities. Implement log data validation, use structured logging with field-level controls, monitor logs for suspicious patterns, and restrict access to log files.',
	'js/log-injection': 'Sanitize and validate all user input before logging by escaping special characters and control sequences. Use logging libraries with built-in sanitization features like Winston with redaction, implement log format validation, and monitor logs for injection attempts and anomalous patterns.',
	'js/timing-attack': 'Use constant-time comparison functions for all sensitive operations, especially credential verification and token validation. Implement artificial delays or random jitter to normalize response times, use crypto.timingSafeEqual() for comparing secrets, and avoid early returns in security-critical comparisons.',
	'js/web-crypto-misuse': 'Use established cryptographic libraries with secure defaults instead of implementing custom crypto. Follow OWASP cryptographic storage guidelines, implement proper key management with secure key generation and storage, use authenticated encryption modes like AES-GCM, and regularly update crypto libraries.',
	'js/microservice-auth-bypass': 'Implement mutual TLS (mTLS) for service-to-service communication in microservice architectures. Use service mesh security features, validate JWT tokens at all service boundaries, implement zero-trust networking principles, and monitor inter-service communication for anomalies.',
	'js/unsafe-external-link': 'Add rel="noopener noreferrer" to all external links to prevent tabnabbing and referrer leakage. Validate external URLs against allowlists where possible, implement link scanning for known malicious domains, use intermediate redirect pages for warnings, and monitor external link usage.',
	'js/missing-csrf-protection': 'Implement anti-CSRF tokens for all state-changing operations using established libraries like csurf. Configure SameSite cookie attributes appropriately, verify Origin and Referer headers for additional protection, implement proper CORS policies, and use double-submit cookie patterns where appropriate.',
	'js/session-fixation': 'Regenerate session identifiers after successful authentication using secure session management libraries. Implement proper session invalidation on logout, use secure session storage mechanisms, set appropriate session timeouts, and monitor for session anomalies and concurrent sessions.',
	'js/clickjacking-vulnerability': 'Implement X-Frame-Options or Content-Security-Policy frame-ancestors directive to prevent embedding in unauthorized frames. Use frame-busting JavaScript as additional protection, implement proper CSRF protection for sensitive actions, and consider using click-jacking detection techniques.'
};

module.exports = {
	mediumRules,
	mediumSeverityRules,
	mediumDescriptions,
	mediumRecommendations,
};